name: Expo Publish App
on:
  push:
    branches:
      - main
    paths:
      - 'game/kegeland/**'
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    env:
      working-directory: ./game/kegeland
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install packages
        run: yarn install
        working-directory: ${{env.working-directory}}
      - name: Publish application
        run: expo publish
        working-directory: ${{env.working-directory}}
